# Generated by Django 5.2.5 on 2025-09-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_closed_at_alter_listing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('removed', 'Removed'), ('won', 'Won')], default='active', max_length=20),
        ),
    ]
